### ISSUE TITLE
panic: runtime error: slice bounds out of range [:-1]

### ISSUE THREAD

**Issue by TokugawaHeavyIndustries** [petergeneric/unifi-protect-remux#7]
This error was generated on x86 ver 3.0.0, with x86 version of ubnt_ubvinfo

```
2020/10/10 16:05:41 Analysing  /remux/ubv.ubv
2020/10/10 16:05:41 First Frame timestamp 2020-04-09 17:28:15.016 +0000 UTC
2020/10/10 16:05:41 Second Frame timestamp 2020-04-09 17:28:15.096 +0000 UTC
2020/10/10 16:05:41 First Frame timestamp 2020-04-09 17:29:18.309 +0000 UTC
2020/10/10 16:05:41 Second Frame timestamp 2020-04-09 17:29:18.389 +0000 UTC
2020/10/10 16:06:18

Analysis complete!
2020/10/10 16:06:18 First Partition:
2020/10/10 16:06:18     Tracks: 1
2020/10/10 16:06:18     Frames: 17
2020/10/10 16:06:18     Start Timecode: 2020-04-09T17:28:15Z
2020/10/10 16:06:18

Extracting 2 partitions
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
main.RemuxCLI(0xc0000ae030, 0x1, 0x1, 0x100, 0x0, 0x1, 0x4ffb74, 0x2)
        /opt/graal/unifi-protect-remux/remux.go:105 +0x1036
main.main()
        /opt/graal/unifi-protect-remux/remux.go:61 +0x2e5
```

**Comment by petergeneric** [comment]
Hi,

Could you please provide the result of ```ubnt_ubvinfo -P -f /remux/ubv.ubv```?

**Comment by petergeneric** [comment]
Fix released: https://github.com/petergeneric/unifi-protect-remux/releases/tag/3.0.1

**Comment by TokugawaHeavyIndustries** [comment]
Hey you're quick, thanks for the fast bugfix! Didn't think about renames being the issue.
